---
defaults:
  - _self_
  - exp: trivial
  - model: medium

training_mode: mcts

mcts:
  simulations: 100
  childs: 30

seed: 0
device: auto
distributed: []
mode: online

hydra:
  job:
    chdir: true
