---
defaults:
  - _self_
  - env: trivial
  - model: medium
  - ppo: default
  - mcts: default

gamma: 0.99

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-2

scheduler:
  warmup_steps: 0
  cosine_t0: 0
  cosine_tmult: 1
  eta_min: 1.0e-6

trainer:
  episodes: -1
  reset_proportion: 0.50
  clip_value: 1.0

checkpoint:

seed: 0
device: auto
distributed: []
mode: online

hydra:
  job:
    chdir: true
