---
defaults:
  - _self_
  - exp: trivial
  - model: medium

training_mode: mcts

mcts:
  simulations: ${exp.trainer.rollouts}
  childs: 10

seed: 0
device: auto
distributed: []
mode: online

hydra:
  job:
    chdir: true
